### ISSUE TITLE
Access GSA Docker Hub

### ISSUE THREAD

**Issue by erniedeeb** [GSA/px-bears-drupal#105]
We are currently creating our own Docker Images for cms and waf applications that we are using in the Sandbox Environment. We cannot use the USAGov images that are already built and available as we need to make slight changes on them to be able to make them work for our case.

Since we are creating new images, we need a GSA provided a repo/hub to store them.

**Comment by erniedeeb** [comment]
We won't be able to use Docker Hub but are investigating using Github Container registry.

**Comment by scottqueen-bixal** [comment]
After our conversation with usa.gov DevOps Lead we have a few action items to take for getting a repository to store our custom docker image.  

> Ok'd to store dev image on ghcr (github container repository), so long as we follow best practice to limit access to any necessary keys.  This is likely going to be implemented in our pipeline via CircleCI.

**@FatmaBakir , let's create  a new ticket to POC ghcr**
- consider using current `px-bears-drupal` repository
- if this works for us, let's write it up on the tech document so that usa.gov tech team has eyes on it https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry
- after local POC, implement in pipeline with CircleCi

**Comment by FatmaBakir** [comment]
@erniedeeb @scottqueen-bixal 
As per USAGov’s recommendation/Instructions we were able to utilize Github Container Registry as part of our repo and all our dev images are on Github Container Registry with Internal(Private) Access:
https://github.com/orgs/GSA/packages
I’ve removed all the dev images from my personal Docker hub.
