### ISSUE TITLE
a11y | color contrast

### ISSUE THREAD

**Issue by scottqueen-bixal** [GSA/px-bears-drupal#507]
8 | 08/31 | Amy | Back link (top left) | Visibility by all users | Light gray is too light; doesn’t pass color contrast; Ernesto Fernandez Alvarez - QQBC-C has suggested a darker gray that passes. |   | “About the applicant” page; about the deceased page | Design | Blank |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
9 | 08/31 | Amy | “Time to complete” text | Visibility by all users | Light gray is too light; doesn’t pass color contrast |   | Main page | Design | Blank |  
10 | 08/31 | Amy | (Required) | Visibility by all users | Light gray is too light; doesn’t pass color contrast |   | About pages | Design | Blank |  
49 | Under Review 9/11/2023 | Ernesto | Time to complete legend color | We changed the color of this legend to 3D4551(Dark Medium Gray) based on Amy’s recommendation to improve usability Severity Rating: 2 | MVP shows a lighter shade of grayhttps://drive.google.com/file/d/12wXnvkERznRFHGQhdOEh7bK5We-mQ3uw/view?usp=drive_link |   | https://drive.google.com/file/d/1rUlakCVfOQMw1LtQk0jHk2FA6Vpxpn5a/view?usp=drive_link | Design |

**Comment by angelina-smith** [comment]
@scottqueen-bixal, reviewed the color contrast for everything above and it all passes! However, I did notice that this bug was skipped over: 

<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-b1810015-7fff-6b11-c791-c36429d9da44"><div dir="ltr" style="margin-left:-44.25pt;" align="left">

19 | 9/5 | Angelina | Keyboard focus indicator for buttons on “Sharing and Printing” results page needs more contrast | Focus indicator on active and hover of the three buttons in the ‘Sharing and Printing’ section needs more contrast between active and inactive state.2.4.11 | Focus indicator on the three buttons in the ‘Sharing and Printing’ section are not consistent with the focus indicator on the ‘Back’ and ‘Continue’ buttons on prior pages. Not enough contrast between active and inactive hover states. | “Your Custom List”, Results page.Edge through VDI | See screenshot item #7. | Development | Blank
-- | -- | -- | -- | -- | -- | -- | -- | -- | --


</div></b>
</body>
</html>19
9/5
 Angelina
Keyboard focus indicator for buttons on “Sharing and Printing” results page needs more contrast
Focus indicator on active and hover of the three buttons in the ‘Sharing and Printing’ section needs more contrast between active and inactive state.

[2.4.11](https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance-minimum)
Focus indicator on the three buttons in the ‘Sharing and Printing’ section are not consistent with the focus indicator on the ‘Back’ and ‘Continue’ buttons on prior pages. 
Not enough contrast between active and inactive hover states. 
“Your Custom List”, Results page.

Edge through VDI
[See screenshot item #7.](https://docs.google.com/document/d/1raRRycSIa5bXTMxe83dCTzJamjglUalsrDUOpn9B77s/edit)
 Development
 Blank
